adding parent path of ESMB.py to Pythonpath, s. #23
shitwolfymakes/Endless-Sky-Mission-Builder pull request #24
Opened 2020-12-31 12:31 UTC by Harald-Berghoff

## Summary
[MINOR]: The parent path to the ESMB.py file is now added to the Pythonpath.

-----------------------
**Bugfix:** This PR addresses issue #23

## Fix Details
The parent path to the ESMB.py file is now added to the Pythonpath. From there the path src will be available to let statements like `from src.model import Mission` always work, no matter from where you are when starting ESMB.py.

Please note that there is still an issue with the editor import on other than the supported environments, which is not a path issue. As it obviously works with Ubuntu and Python 3.7 (as opposed to my configuration Fedora 33 with Python 3.9). Anyway the issue was the subject of #20.

@MCOfficer : change the target branch or repo as you think fits.

2020-12-31 14:37 UTC, MCOfficer commented
Thanks for the PR!

One misconception: I'm just a contributor. I have input & ideas, but ultimately it's all wolfy's call ;)

2020-12-31 15:03 UTC, shitwolfymakes commented
Hey guys, just now getting to this. I'll take a look after work. This will be a great stopgap while I work on the stuff I will be outlining in the year end post.

Thanks!

2021-01-01 13:19 UTC, Harald-Berghoff commented
Maybe I should give some more explanation what I did in the two commits:
The first commit is what I thought should solve the issue of the 'no module src' error. The PyInstaller does something similar and due to the fact the build on Ubuntu was working I thought that's it. Also the remaining error with the impprt of the editor was already reported, when the build still worked.
But on my system I wasn't able to create a working build, which is odd given that Python normally doesn't show this differences and I digged a little deeper into the issue (my single directory build also reported the editor import error). I found this website very helpful (http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html), and my guess is that it is the [The double import trap](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-double-import-trap). The pattern of imports supported that assumption, so i tried it and it worked. I just had to add the src dir to the PyInstaller command but from there on i could run the editor like this: `python src/ESMB.py` and the build was also fine (I started everything in the root dir of the repo). All required changes (still straight forward) are in the second commit.

You may still have to check it with PyCharme, but for me it is working in VSCode and the console.

2021-01-03 06:43 UTC, shitwolfymakes requested changes
If this line is no longer relevant, go ahead and remove it entirely to prevent confusion. This seems to work on Pycharm for me, so once this is dealt with I'll test it again on my various boxes and merge if it still works. Thanks mate!

2021-01-03 06:43 UTC, shitwolfymakes commented on src/ESMB.py
> +#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
Taking lunch to check this out. Is this now commented out to avoid duplicate additions on each run? If so, is there a check you can make to see if it is already in the Pythonpath, and run this line if it isn't?

2021-01-03 11:45 UTC, Harald-Berghoff commented on src/ESMB.py
> +#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
Your are right, this line is no longer needed, I removed it. I used that to solve the issue with no module src, but it caused the duplicate import issue. After fixing this line is now unneeded.

2021-01-03 23:30 UTC, shitwolfymakes commented on src/ESMB.py
> +#sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)))
Awesome, thanks

2021-01-05 17:29 UTC, shitwolfymakes approved these changes

2021-01-08 01:20 UTC, shitwolfymakes commented
Tested and working on my MacBook Pro running Catalina. Will test on Windows later

2021-03-04 01:07 UTC, shitwolfymakes commented
Tested on Windows and confirmed working. Testing on linux in a second. Sorry this took so long,, I've been swamped!

2021-03-04 01:49 UTC, shitwolfymakes commented
Tested on Linux and confirmed working. @Harald-Berghoff thank you so much for fixing this!

2021-03-04 01:49 UTC, merged